#!/bin/bash

version_info="oveja 1.0.0"

#Colors
red='\e[1;31m'
bold='\e[1m'
def='\e[0m'

#User-Agent, puedes cambiarlo si lo deseas
user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:138.0) Gecko/20100101 Firefox/138.0"

#Reproductor (testeados: mpv, vlc, ffplay)
player="mpv"

#Directorio de descargas
dir_descargas="$HOME"

trap ctrl_c INT; function ctrl_c(){ exit 3; }

function help(){
	echo -e "${bold}Usage: oveja$def [OPTIONS]"
	echo -e "${bold}Options:$def"
	echo -e "$bold  -c, --continuar$def\tContinuar anime"
	echo -e "$bold  -l, --logs$def\t\tVer logs"
	echo -e "$bold  -h, --help$def\t\tPrint help"
	echo -e "$bold  -v, --version$def\t\tPrint version"
	exit 0
}

#Logs: anime/capitulo_visto
function read_logs(){
	anime_select=$(cat "$HOME/.config/oveja/logs.txt" | fzf --reverse --cycle --prompt "logs: ")
	watch_anime "$anime_select"
	exit 0
}

#Buscar anime
function search_anime(){
	frontend=$(echo -e "AnimeAV1\nJkAnime\nMonosChinos2\nAnimeFLV\nTioAnime" | fzf --reverse --cycle --prompt "Selecciona un Frontend: ")
	case "$frontend" in
		"AnimeAV1")
			curl -s -A "$user_agent" "https://animeav1.com/catalogo?search=$1" -o/tmp/oveja/response; wait
			cat /tmp/oveja/response | htmlq 'a.inset-0' -a href | awk '{print $NF}' FS='/' >/tmp/oveja/anime_name
			if [[ $(< /tmp/oveja/response) =~ "page=" ]]; then
				curl -s -A "$user_agent" "https://animeav1.com/catalogo?search=$1&page=2" | htmlq 'a.inset-0' -a href | awk '{print $NF}' FS='/' >>/tmp/oveja/anime_name
			fi
			anime_name=$(cat /tmp/oveja/anime_name | fzf --reverse --cycle --prompt "Selecciona un anime: ")
			anime_caps=$(curl -s -A "$user_agent" "https://animeav1.com/media/$anime_name" | grep -oP 'episodesCount:\K\d+')
			if [ $anime_caps -eq 0 ]; then
				echo "${red}Este anime no tiene ningun capitulo publicado. Verifica en MyAnimeList o Anilist para cerciorarte de esto, o reportalo como falla en github.com/user/issues/${def}"; exit 2
        	fi
        	select_cap=$(seq 1 $anime_caps | fzf --reverse --cycle --prompt "Selecciona un capitulo: ")
        	curl -s -A "$user_agent" "https://animeav1.com/media/$anime_name/$select_cap/__data.json?x-sveltekit-invalidated=0001" | jq -r '.. | strings' | awk '/^http/ {print (s?s:"Unknown"), $0; s=""} !/^http/ {s=$0}' | nl -w1 -s ' ' > /tmp/oveja/mirror
        	mirror=$(cat /tmp/oveja/mirror | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
        	play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$select_cap" "$anime_caps" "$frontend"
        	exit 0
		;;
    	"JkAnime")
        	anime_name=$(curl -s -A "$user_agent" "https://jkanime.net/buscar/$1" | htmlq 'div.anime__item' | htmlq a -a href | awk '!seen[$0]++' | awk '{print $4}' FS=/ | fzf --reverse --cycle --prompt "Selecciona un anime: ")
        	curl -s -A "$user_agent" "https://jkanime.net/$anime_name" -o/tmp/oveja/response; wait
        	anime_caps=$(cat /tmp/oveja/response | grep "Episodios:" -m1 | awk '{print $4}' FS='>' | awk '{print $1}' 'FS=<' | head -n1 | tr -d '[:space:]')
        	if [ $anime_caps -eq 0 ]; then
        		anime_caps=$(cat /tmp/oveja/response | grep "Último" | htmlq a -t | awk '{print $4}')
        		if [ $anime_caps -eq 0 ]; then
        			echo-e  "${red}Este anime no tiene ningun capitulo publicado. Verifica en MyAnimeList o Anilist para cerciorarte de esto, o reportalo como falla en github.com/user/issues/${def}"; exit 2
        		fi
        	fi
        	select_cap=$(seq 1 $anime_caps | fzf --reverse --cycle --prompt "Seleciona un capitulo: ")
        	curl -s -A "$user_agent" "https://jkanime.net/$anime_name/$select_cap/" -o/tmp/oveja/response; wait
        	cat /tmp/oveja/response | grep "var servers" | htmlq --text | sed 's/.$//; s/var servers = //' | jq -r '.[] | "\(.server) \(.remote | @base64d)"' | grep -v '^$' | nl -w 1 -s ' ' > /tmp/oveja/mirror
        	mirror=$(cat /tmp/oveja/mirror | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
			#play_anime MIRROR LINK_MIRROR NOMBRE_ANIME CAPITULO_ANIME CAPITULOS_TOTALES FRONTEND
        	play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$select_cap" "$anime_caps" "$frontend"
        	exit 0
        ;;
    	"MonosChinos2")
			curl -s -A "$user_agent" "https://monoschino2.com/directorio/anime?q=$1" -o/tmp/oveja/response; wait
			cat /tmp/oveja/response | htmlq 'article' | htmlq a -a href | awk '{print "https://monoschino2.com/" $1}' >/tmp/oveja/anime_name
			cat /tmp/oveja/response | htmlq 'img.skeleton' -a alt > /tmp/oveja/anime_list
			if [[ $(< /tmp/oveja/response) =~ "p=2" ]]; then
				curl -s -A "$user_agent" "https://monoschino2.com/directorio/anime?p=2&q=$1" -o/tmp/oveja/response; wait
				cat /tmp/oveja/response | htmlq 'article' | htmlq a -a href | awk '{print "https://monoschino2.com/" $1}' >>/tmp/oveja/anime_name
				cat /tmp/oveja/response | htmlq 'img.skeleton' -a alt >> /tmp/oveja/anime_list
			fi
			anime_name=$(cat /tmp/oveja/anime_list | nl -w 1 | fzf --reverse --cycle --prompt "Selecciona un anime: ")
			anime_link=$(sed -n "$(echo "$anime_name" | cut -f1)p" /tmp/oveja/anime_name)
			anime_caps=$(curl -s -A "$user_agent" "$anime_link" | htmlq 'button.mt-2' -t | tail -n1 | awk '{print $NF}')
			if [ $anime_caps -eq 0 ]; then
				echo -e "${red}Este anime no tiene ningun capitulo publicado. Verifica en MyAnimeList o Anilist para cerciorarte de esto, o reportalo como falla en github.com/user/issues/${def}"; exit 2
			fi
			anime_name="${anime_link##*/}"
			select_cap=$(seq 1 $anime_caps | fzf --reverse --cycle --prompt "Selecciona un capitulo: ")
			curl -s -A "$user_agent" "https://monoschino2.com/ver/${anime_name}-${select_cap}" -o/tmp/oveja/response; wait
			paste <(cat /tmp/oveja/response | grep 'span class="icon' -A1 | grep "<span>" | htmlq -t | sed 's/\ //g' | grep -v "^$") <(cat /tmp/oveja/response | grep 'tabsArray\[' | awk '{print $10}' FS="'" | grep -v '^$' | awk '{print "https" $NF}' FS='https') -d ' ' > /tmp/oveja/mirror
			mirror=$(cat /tmp/oveja/mirror | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
			play_anime "$(echo $mirror | awk '{print $1}')" "$(echo $mirror | awk '{print $2}')" "$anime_name" "$select_cap" "$anime_caps" "$frontend"
			exit 0
    	;;
		"AnimeFLV")
			anime_name=$(curl -s -A "$user_agent" "https://www4.animeflv.net/browse?q=$1" | htmlq 'a.Vrnmlk' -a href | awk '{print $NF}' FS='/' | fzf --reverse --cycle --prompt "Seleciona un anime: ")
			anime_caps=$(curl -s -A "$user_agent" "https://www4.animeflv.net/anime/$anime_name" | grep "var episodes " | awk '{print $1}' FS=']' | awk '{print $3}' FS='[' | awk '{print $1}' FS=',')
			if [ $anime_caps -eq 0 ]; then
				echo -e "${red}Este anime no tiene ningun capitulo publicado. Verifica en MyAnimeList o Anilist para cerciorarte de esto, o reportalo como falla en github.com/user/issues/${def}"; exit 2
			fi
			select_cap=$(seq 1 $anime_caps | fzf --reverse --cycle --prompt "Selecciona un capitulo: ")
			curl -s -A "$user_agent" "https://www4.animeflv.net/ver/${anime_name}-${select_cap}" | grep "var videos = {" | sed 's/        var videos = //; s/..$//' | jq -r '.SUB[] | "\(.title)\t\(.code)"' | nl -w1 -s ' ' > /tmp/oveja/mirror
			mirror=$(cat /tmp/oveja/mirror | fzf --reverse --cycle --prompt "Seleccione un mirror: ")
			play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$select_cap" "$anime_caps" "$frontend"
			exit 0
        ;;
	    "Katanime")
	    	echo -e "${red}Actualmente estoy trabajando en esta opcion...${def}"; exit 2
        ;;
    	"TioAnime")
    		anime_name=$(curl -s -A "$user_agent" "https://tioanime.com/directorio?q=$1" | htmlq 'article.anime' | htmlq a -a href | awk '{print $NF}' FS='/' | fzf --reverse --cycle --prompt "Selecciona un anime: ")
    		anime_caps=$(curl -s -A "$user_agent" "https://tioanime.com/anime/$anime_name" | grep "var episodes " | awk '{print $1}' FS=',' | awk '{print $NF}' FS='[' )
    		if [ $anime_caps -eq 0 ];then
    			echo "${red}Este anime no tiene ningun capitulo publicado. Verifica en MyAnimeList o Anilist para cerciorarte de esto, o reportalo como falla en github.com/user/issues/${def}"; exit 2
    		fi
    		select_cap=$(seq 1 $anime_caps | fzf --reverse --cycle --prompt "Seleccione un capitulo: ")
    		curl -s -A "$user_agent" "https://tioanime.com/ver/${anime_name}-${select_cap}" | grep "var videos" | sed 's/    var videos = //; s/..$//' | jq -r '.[] | "\(.[0]) \(.[1])"' | nl -w 1 -s ' ' > /tmp/oveja/mirror
    		mirror=$(cat /tmp/oveja/mirror| fzf --reverse --cycle --prompt "Seleccione un mirror: ")
    		play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$select_cap" "$anime_caps" "$frontend"
    		exit 0
        ;;
    	*)
        echo "${red}Unknow Frontend!${def}"; exit 1;;
	esac
}

function play_anime(){
	echo "$6: $3 $4" >> $HOME/.config/oveja/logs.txt
	echo -e "${bold}Obteniendo el link...${def}"
	case "$1" in
		"Mediafire")
			fix_url=${2/:\/\//:\/\/www.}
			index_link=$(curl -s -A "$user_agent" "$fix_url" | htmlq 'a.popsok' -a href)
			if [ "$index_link" == "" ]; then
				echo -e "${red}404! El link esta caido, prueba otro mirror/frontend${def}"; sleep 2
				anime_options "$1" "$2" "$3" "$4" "$5" "$6"
			fi
			case "$player" in
				"mpv")
    				mpv --user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
        		"vlc")
    				vlc --http-user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
    			"ffplay")
    				ffplay -headers "User-Agent: $user_agent"$'\r\n' "$index_link" &>/dev/null &
    			;;
    			*)
    				echo -e "${red}$play no esta soportado${def}"; exit 4
    			;;
    		esac
			echo -e "${bold}Reproduciendo...${def}"; sleep 1.2
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			exit 0
		;;
		"Mega" | "MEGA")
			echo -e "${bold}Mega${def} no esta soportado para descarga directa ni reproduccion directa, debes descargarlo/verlo desde su propia pagina.\nDeseas abrir tu Browser por defecto con este link? -> ${bold}$2${def}"
			abrir_navegador=$(echo -e "Si\nNo" | fzf --height 5)
			if [ "$abrir_navegador" == "Si" ]; then xdg-open "$2"; fi
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "0"
			exit 0
		;;
		"Streamwish" | "SW")
			curl -s -A "$user_agent" "$2" -I >/tmp/oveja/response; wait
			redirect_link=$(cat /tmp/oveja/response | grep 'location' | awk '{print $2}' | sed 's/\r//')
			referer=$(cat /tmp/oveja/response | grep "location" | awk '{print $NF}' | awk '{print $1}' FS="embed" | awk '{print $1}' FS="e/")
			master_link=$(curl -s -H "Referer: https://streamwish.to" -H "User-Agent: $user_agent" "$redirect_link" | grep "eval" | htmlq script -t | grep -v '^$' | js-beautify | grep "master.m3u8" | awk '{print $4}' FS='"' | sed 's/master.m3u8\//master.m3u8/' | grep "^http")
			index=$(curl -s -H "Referer: $referer" -H "User-Agent: $user_agent" "$master_link" | awk NR==3)
			base="${master_link%master.m3u8*}"
			index_link="${base}${index}"
			if [ "$index_link" == "" ]; then
				echo -e "${red}404! El link esta caido, prueba otro mirror/frontend${def}"; sleep 2
				anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			fi
			case "$player" in
				"mpv")
    				mpv --http-header-fields="Referer: $referer" --user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
        		"vlc")
    				vlc --http-referrer="$referer" --http-user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
    			"ffplay")
    				ffplay -headers "Referer: $referer"$'\r\n'"User-Agent: $user_agent"$'\r\n' "$index_link" &>/dev/null &
    			;;
    			*)
    				echo -e "${red}$play no esta soportado${def}"; exit 4
    			;;
    		esac
			#anime_options MIRROR LINK_MIRROR NOMBRE_ANIME CAPITULO_ANIME CAPITULOS_TOTALES FRONTEND
			echo -e "${bold}Reproduciendo...${def}"; sleep 1.2
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			exit 0
		;;
		"VOE" | "Voex")
			echo -e "${bold}VOE${def} no esta soportado para descarga directa ni reproduccion directa, debes descargarlo/verlo desde su propia pagina.\nDeseas abrir tu Browser por defecto con este link? -> ${bold}$2${def}"
			abrir_navegador=$(echo -e "Si\nNo" | fzf --height 5)
			if [ "$abrir_navegador" == "Si"]; then xdg-open "$2"; fi
			exit 4
		;;
		"Vidhide")
			curl -s -A "$user_agent" "$2" -I >/tmp/oveja/response; wait
			redirect_link=$(cat /tmp/oveja/response | grep 'location' | awk '{print $2}' | sed 's/\r//')
			referer=$(cat /tmp/oveja/response | grep "location" | awk '{print $NF}' | awk '{print $1}' FS="embed" | awk '{print $1}' FS="e/")
			master_link=$(curl -s "$redirect_link" -A "$user_agent" | grep "master" | js-beautify | grep "master.txt" | awk '{print $4}' FS='"')
			index=$(curl -s -H "Referer: $referer" -H "User-Agent: $user_agent" "$master_link" | awk NR==3)
			base="${master_link%master*}"
			index_link="${base}${index}"
			if [ "$index_link" == "" ]; then
				echo -e "${red}404! El link esta caido, prueba otro mirror/frontend${def}"; sleep 2
				anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			fi
			case "$player" in
				"mpv")
    				mpv --http-header-fields="Referer: $referer" --user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
        		"vlc")
    				vlc --http-referrer="$referer" --http-user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
    			"ffplay")
    				ffplay -headers "Referer: $referer"$'\r\n'"User-Agent: $user_agent"$'\r\n' "$index_link" &>/dev/null &
    			;;
    			*)
    				echo -e "${red}$play no esta soportado${def}"; exit 4
    			;;
    		esac
			echo -e "${bold}Reproduciendo...${def}"; sleep 1.2
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			exit 0
		;;
		"Mixdrop")
			curl -s -A "$user_agent" "$2" -I >/tmp/oveja/response; wait
			redirect_link=$(cat /tmp/oveja/response | grep 'location' | awk '{print $2}' | sed 's/\r//')
			referer=$(cat /tmp/oveja/response | grep "location" | awk '{print $NF}' | awk '{print $1}' FS="embed" | awk '{print $1}' FS="e/")
			index_link=$(curl -s -A "$user_agent" "$redirect_link" | htmlq script -t | grep "eval" | js-beautify | grep wurl | awk '{print "https:" $2}' FS='"')
			if [ "$index_link" == "" ]; then
				echo -e "${red}404! El link esta caido, prueba otro mirror/frontend${def}"; sleep 2
				anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			fi
			case "$player" in
				"mpv")
    				mpv --http-header-fields="Referer: $referer" --user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
        		"vlc")
    				vlc --http-referrer="$referer" --http-user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
    			"ffplay")
    				ffplay -headers "Referer: $referer"$'\r\n'"User-Agent: $user_agent"$'\r\n' "$index_link" &>/dev/null &
    			;;
    			*)
    				echo -e "${red}$play no esta soportado${def}"; exit 4
    			;;
    		esac
			echo -e "${bold}Reproduciendo...${def}"; sleep 1.2
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			exit 0
		;;
		"Mp4upload" | "Mp4Upload" | "MP4Upload")
			index_link=$(curl -s -A "$user_agent" "$2" | grep "video\.mp4" | awk '{print $2}' FS='"')
			if [ "$index_link" == "" ]; then
				echo -e "${red}404! El link esta caido, prueba otro mirror/frontend${def}"; sleep 2
				anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			fi
			case "$player" in
				"mpv")
    				mpv --http-header-fields="Referer: https://www.mp4upload.com/" --user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
        		"vlc")
    				vlc --http-referrer="https://www.mp4upload.com/" --http-user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
    			"ffplay")
    				ffplay -headers "Referer: https://www.mp4upload.com/"$'\r\n'"User-Agent: $user_agent"$'\r\n' "$index_link" &>/dev/null &
    			;;
    			*)
    				echo -e "${red}$play no esta soportado${def}"; exit 4
    			;;
    		esac
			echo -e "${bold}Reproduciendo...${def}"; sleep 1.2
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			exit 0
		;;
		"Streamtape" | "StreamTape" | "Stape ")
			redirect_link=$(curl -s -A "$user_agent" "$2" | htmlq 'div[id="ideoolink"]' -t | awk '{print "https:/" $1 "&stream=1"}')
			index_link=$(curl -s "$redirect_link" -H "Host: streamtape.com" -H "User-Agent: $user_agent" -H "Referer: $redirect_link" | grep location | awk '{print $NF}')
			if [ "$index_link" == "" ]; then
				echo -e "${red}404! El link esta caido, prueba otro mirror/frontend${def}"; sleep 2
				anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			fi
			case "$player" in
				"mpv")
    				mpv --http-header-fields="Referer: https://streamtape.com/" --user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
        		"vlc")
    				vlc --http-referrer="https://streamtape.com/" --http-user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
    			"ffplay")
    				ffplay -headers "Referer: https://streamtape.com/"$'\r\n'"User-Agent: $user_agent"$'\r\n' "$index_link" &>/dev/null &
    			;;
    			*)
    				echo -e "${red}$play no esta soportado${def}"; exit 4
    			;;
    		esac
			echo -e "${bold}Reproduciendo...${def}"; sleep 1.2
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			exit 0
		;;
		"Doodstream")
			echo -e "${red}Actualmente estoy trabajando en esta opcion...${def}"; exit 2
		#	curl -s -A "$user_agent" "$2" -I >/tmp/oveja/response; wait
		#	redirect_link=$(cat /tmp/oveja/response | grep 'location' | awk '{print $2}' | sed 's/\r//')
		#	referer=$(cat /tmp/oveja/response | grep "location" | awk '{print $NF}' | awk '{print $1}' FS="embed" | awk '{print $1}' FS="e/")
		;;
		"PremiunVIP")
			face_id="${2##*=}"
			base="https://huggingface.co/ElRompeAnosFullAnal/ElRompeAnosFullAnal/resolve/main/"
			index_link=$(curl -s -A "$user_agent" "${base}${face_id}.mp4" -I | grep "location" | awk '{print $NF}' | tr -d '[:space:]')
			if [ "$index_link" == "" ]; then
				echo -e "${red}404! El link esta caido, prueba otro mirror/frontend${def}"; sleep 2
				anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			fi
			case "$player" in
				"mpv")
    				mpv --user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
        		"vlc")
    				vlc --http-user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
    			"ffplay")
    				ffplay -headers "User-Agent: $user_agent"$'\r\n' "$index_link" &>/dev/null &
    			;;
    			*)
    				echo -e "${red}$play no esta soportado${def}"; exit 4
    			;;
    		esac
			echo -e "${bold}Reproduciendo...${def}"; sleep 1.4
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			exit 0
		;;
		"PlusTube")
			master_link=$(curl -s -A "$user_agent" "$2" | htmlq script -t | grep "eval(atob" | sed "s/.*atob('\([^']*\)'.*/\1/" | perl -MMIME::Base64 -ne '$pass1 = decode_base64($_); $pass2 = join("", map { chr(ord($_) - 1) } split //, $pass1); print decode_base64($pass2);' | grep "video.src" | awk '{print $2}' FS="'")
			index_link=$(curl -s -A "$user_agent" "$master_link" | awk NR==3)
			if [ "$index_link" == "" ]; then
				echo -e "${red}404! El link esta caido, prueba otro mirror/frontend${def}"; sleep 2
				anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			fi
			case "$player" in
				"mpv")
    				mpv --http-header-fields="Referer: https://re.ironhentai.com" --user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
        		"vlc")
    				vlc --http-referrer="https://re.ironhentai.com" --http-user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
    			"ffplay")
    				ffplay -headers "Referer: https://re.ironhentai.com"$'\r\n'"User-Agent: $user_agent"$'\r\n' "$index_link" &>/dev/null &
    			;;
    			*)
    				echo -e "${red}$play no esta soportado${def}"; exit 4
    			;;
    		esac
			echo -e "${bold}Reproduciendo...${def}"; sleep 1.2
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			exit 0
		;;
		"SaveFiles")
			file_code=${2##*/}
			referer=${2%/e/*}
			master_link=$(curl -s "$referer/dl" -X POST -H "User-Agent: $user_agent" --data-binary "op=embed&file_code=${file_code}&auto=1&referer=" | grep "master" | awk '{print $2}' FS='"')
			index_link=$(curl -s -A "$user_agent" "$master_link" | awk NR==3)
			if [ "$index_link" == "" ]; then
				echo -e "${red}404! El link esta caido, prueba otro mirror/frontend${def}"; sleep 2
				anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			fi
			case "$player" in
				"mpv")
    				mpv --http-header-fields="Referer: $referer" --user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
        		"vlc")
    				vlc --http-referrer="$referer" --http-user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
    			"ffplay")
    				ffplay -headers "Referer: $referer"$'\r\n'"User-Agent: $user_agent"$'\r\n' "$index_link" &>/dev/null &
    			;;
    			*)
    				echo -e "${red}$play no esta soportado${def}"; exit 4
    			;;
    		esac
			echo -e "${bold}Reproduciendo...${def}"; sleep 1.2
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			exit 0
		;;
		"YourUpload")
			index_link=$(curl -s -A "$user_agent" "$2" | grep "file: " -m1 | awk '{print $2}' FS="'")
			if [ "$index_link" == "" ]; then
				echo -e "${red}404! El link esta caido, prueba otro mirror/frontend${def}"; sleep 2
				anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			fi
			case "$player" in
				"mpv")
    				mpv --http-header-fields="Referer: https://www.yourupload.com/" --user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
        		"vlc")
    				vlc --http-referrer="https://www.yourupload.com/" --http-user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
    			"ffplay")
    				ffplay -headers "Referer: https://www.yourupload.com/"$'\r\n'"User-Agent: $user_agent"$'\r\n' "$index_link" &>/dev/null &
    			;;
    			*)
    				echo -e "${red}$play no esta soportado${def}"; exit 4
    			;;
    		esac
			echo -e "${bold}Reproduciendo...${def}"; sleep 1.2
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			exit 0
		;;
		"Netu" | "Okru" | "Fembed" | "HQQ")
			echo -e "${red}Usualmente los links de Netu, Okru, Fembed, Hqq estan caidos. No ocupes estas opciones, solo los dejo por si en un futuro funcionan FF${def}"
			exit 4
		;;
		"HLS")
			index_link=${2/\/play\//\/m3u8\/}
			if [ "$index_link" == "" ]; then
				echo -e "${red}404! El link esta caido, prueba otro mirror/frontend${def}"; sleep 2
				anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			fi
			case "$player" in
				"mpv")
    				mpv --user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
        		"vlc")
    				vlc --http-user-agent="$user_agent" "$index_link" &>/dev/null &
        		;;
    			"ffplay")
    				ffplay -headers "User-Agent: $user_agent"$'\r\n' "$index_link" &>/dev/null &
    			;;
    			*)
    				echo -e "${red}$play no esta soportado${def}"; exit 4
    			;;
    		esac
			echo -e "${bold}Reproduciendo...${def}"; sleep 1.2
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$index_link"
			exit 0
		;;
		"UPNShare" | "1Fichier")
			echo -e "${bold}UPNShare/1Fichier${def} no esta soportado para descarga directa ni reproduccion directa, debes descargarlo/verlo desde su propia pagina.\nDeseas abrir tu Browser por defecto con este link? -> ${bold}$2${def}"
			abrir_navegador=$(echo -e "Si\nNo" | fzf --height 5)
			if [ "$abrir_navegador" == "Si" ]; then xdg-open "$2"; fi
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "0"
			exit 0
		;;
		"Unknown")
			echo -e "Deseas abrir tu Browser por defecto con este link? -> ${bold}$2${def}"
			abrir_navegador=$(echo -e "Si\nNo" | fzf --height 5)
			if [ "$abrir_navegador" == "Si" ]; then xdg-open "$2"; fi
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "0"
			exit 0
		;;
		*)
			echo -e "${red}Este mirror no ha sido agregado, verifica posibles actualizaciones en Github o abre un issue.${def}"
			echo -e "Log:\nMirror: $1\nUrl: $2\nFrontend: $6"
			exit 4
		;;
	esac
	echo -e "${red}Error en mirror!${def}"
	exit 3
}

function anime_options(){
	option_select=$(echo -e "next\nprevious\nselect\nchange_mirror\ndownload\nquit" | fzf --reverse --cycle --prompt "Reproduciendo episodio $4 de $3 ($5 episodios)")
	case "$option_select" in
		"next")
			next_cap=$(( $4 + 1 ))
			case "$6" in
				"JkAnime")
					mirror=$(curl -s -A "$user_agent" "https://jkanime.net/$3/$next_cap" | grep "var servers" | htmlq --text | sed 's/.$//; s/var servers = //' | jq -r '.[] | "Server: \(.server) Link: \(.remote | @base64d)"' | grep -v '^$' | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$3" "$next_cap" "$5" "$6"
					exit 0
				;;
				"AnimeAV1")
					mirror=$(curl -s -A "$user_agent" "https://animeav1.com/media/$anime_name/$next_cap/__data.json?x-sveltekit-invalidated=0001" | jq -r '.. | strings' | awk '/^http/ {print (s?s:"Unknown"), $0; s=""} !/^http/ {s=$0}' | nl -w1 -s ' ' | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"MonosChinos2")
					curl -s -A "$user_agent" "https://monoschino2.com/ver/${anime_name}-${next_cap}" -o/tmp/oveja/response; wait
					mirror=$(paste <(cat /tmp/oveja/response | grep 'span class="icon' -A1 | grep "<span>" | htmlq -t | sed 's/\ //g' | grep -v "^$") <(cat /tmp/oveja/response | grep 'tabsArray\[' | awk '{print $10}' FS="'" | grep -v '^$' | awk '{print "https" $NF}' FS='https') -d ' ' | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $1}')" "$(echo $mirror | awk '{print $2}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"AnimeFLV")
					mirror=$(curl -s -A "$user_agent" "https://www4.animeflv.net/ver/${anime_name}-${next_cap}" | grep "var videos = {" | sed 's/        var videos = //; s/..$//' | jq -r '.SUB[] | "\(.title)\t\(.code)"' | nl -w1 -s ' ' | fzf --reverse --cycle --prompt "Seleccione un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"TioAnime")
					mirror=$(curl -s -A "$user_agent" "https://tioanime.com/ver/${anime_name}-${next_cap}" | grep "var videos" | sed 's/    var videos = //; s/..$//' | jq -r '.[] | "\(.[0]) \(.[1])"' | nl -w 1 -s ' ' | fzf --reverse --cycle --prompt "Seleccione un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
			esac
		;;
		"previous")
			next_cap=$(( $4 - 1 ))
			case "$6" in
				"JkAnime")
        			mirror=$(curl -s -A "$user_agent" "https://jkanime.net/$3/$next_cap" | grep "var servers" | htmlq --text | sed 's/.$//; s/var servers = //' | jq -r '.[] | "Server: \(.server) Link: \(.remote | @base64d)"' | grep -v '^$' | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
        			play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$3" "$next_cap" "$5" "$6"
        			exit 0
				;;
				"AnimeAV1")
					mirror=$(curl -s -A "$user_agent" "https://animeav1.com/media/$anime_name/$next_cap/__data.json?x-sveltekit-invalidated=0001" | jq -r '.. | strings' | awk '/^http/ {print (s?s:"Unknown"), $0; s=""} !/^http/ {s=$0}' | nl -w1 -s ' ' | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"MonosChinos2")
					curl -s -A "$user_agent" "https://monoschino2.com/ver/${anime_name}-${next_cap}" -o/tmp/oveja/response; wait
					mirror=$(paste <(cat /tmp/oveja/response | grep 'span class="icon' -A1 | grep "<span>" | htmlq -t | sed 's/\ //g' | grep -v "^$") <(cat /tmp/oveja/response | grep 'tabsArray\[' | awk '{print $10}' FS="'" | grep -v '^$' | awk '{print "https" $NF}' FS='https') -d ' ' | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $1}')" "$(echo $mirror | awk '{print $2}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"AnimeFLV")
					mirror=$(curl -s -A "$user_agent" "https://www4.animeflv.net/ver/${anime_name}-${next_cap}" | grep "var videos = {" | sed 's/        var videos = //; s/..$//' | jq -r '.SUB[] | "\(.title)\t\(.code)"' | nl -w1 -s ' ' | fzf --reverse --cycle --prompt "Seleccione un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"TioAnime")
					mirror=$(curl -s -A "$user_agent" "https://tioanime.com/ver/${anime_name}-${next_cap}" | grep "var videos" | sed 's/    var videos = //; s/..$//' | jq -r '.[] | "\(.[0]) \(.[1])"' | nl -w 1 -s ' ' | fzf --reverse --cycle --prompt "Seleccione un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
			esac
		;;
		"select")
			next_cap=$(seq 1 $5 | fzf --reverse --cycle --prompt "Selecciona un capitulo: ")
			case "$6" in
				"JkAnime")
        			mirror=$(curl -s -A "$user_agent" "https://jkanime.net/$3/$next_cap" | grep "var servers" | htmlq --text | sed 's/.$//; s/var servers = //' | jq -r '.[] | "Server: \(.server) Link: \(.remote | @base64d)"' | grep -v '^$' | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
        			play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$3" "$next_cap" "$5" "$6"
        			exit 0
				;;
				"AnimeAV1")
					mirror=$(curl -s -A "$user_agent" "https://animeav1.com/media/$anime_name/$next_cap/__data.json?x-sveltekit-invalidated=0001" | jq -r '.. | strings' | awk '/^http/ {print (s?s:"Unknown"), $0; s=""} !/^http/ {s=$0}' | nl -w1 -s ' ' | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"MonosChinos2")
					curl -s -A "$user_agent" "https://monoschino2.com/ver/${anime_name}-${next_cap}" -o/tmp/oveja/response; wait
					mirror=$(paste <(cat /tmp/oveja/response | grep 'span class="icon' -A1 | grep "<span>" | htmlq -t | sed 's/\ //g' | grep -v "^$") <(cat /tmp/oveja/response | grep 'tabsArray\[' | awk '{print $10}' FS="'" | grep -v '^$' | awk '{print "https" $NF}' FS='https') -d ' ' | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $1}')" "$(echo $mirror | awk '{print $2}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"AnimeFLV")
					mirror=$(curl -s -A "$user_agent" "https://www4.animeflv.net/ver/${anime_name}-${next_cap}" | grep "var videos = {" | sed 's/        var videos = //; s/..$//' | jq -r '.SUB[] | "\(.title)\t\(.code)"' | nl -w1 -s ' ' | fzf --reverse --cycle --prompt "Seleccione un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"TioAnime")
					mirror=$(curl -s -A "$user_agent" "https://tioanime.com/ver/${anime_name}-${next_cap}" | grep "var videos" | sed 's/    var videos = //; s/..$//' | jq -r '.[] | "\(.[0]) \(.[1])"' | nl -w 1 -s ' ' | fzf --reverse --cycle --prompt "Seleccione un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
			esac
		;;
		"change_mirror")
			case "$6" in
				"JkAnime")
					mirror=$(cat /tmp/oveja/mirror | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$3" "$next_cap" "$5" "$6"
				;;
				"AnimeAV1")
					mirror=$(cat /tmp/oveja/mirror | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"MonosChinos2")
					mirror=$(cat /tmp/oveja/mirror | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $1}')" "$(echo $mirror | awk '{print $2}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"AnimeFLV")
					mirror=$(cat /tmp/oveja/mirror | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
				"TioAnime")
					mirror=$(cat /tmp/oveja/mirror | fzf --reverse --cycle --prompt "Selecciona un mirror: ")
					play_anime "$(echo $mirror | awk '{print $2}')" "$(echo $mirror | awk '{print $NF}')" "$anime_name" "$next_cap" "$anime_caps" "$frontend"
				;;
			esac
		;;
		"download")
			if type -p yt-dlp &>/dev/null; then
				if [ "$7" == "0" ]; then
					echo -e "${red}Este mirror no esta programado para descarga directa, ve a su pagina y descargalo -> $2${def}"
				else
					yt-dlp --user-agent "$user_agent" -P "$dir_descargas" -o "$3_$4.%(ext)s" --concurrent-fragments 5 "$7"
				fi
				anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$7"
			fi
			echo -e "${red}Error! yt-dlp no esta instalado, o no esta en tu path!${def}"
			anime_options "$1" "$2" "$3" "$4" "$5" "$6" "$7"
		;;
		"quit") exit 0;;
	esac; exit 0
}

function read_logs(){
	cat $HOME/.config/oveja/logs.txt | fzf --reverse --cycle --prompt "Selecciona un anime para continuar: "
	echo -e "${bold}Funcion de logs pronto... 🐑${def}"
	exit 0
}

function continuar_anime(){
	tail -n1 $HOME/.config/oveja/logs.txt
	echo -e "${bold}Funcion de continuar anime pronto... 🐑 ${def}"
	exit 0
}

while getopts ":-:clhv" opt; do
	case $opt in
		c)continuar_anime;;
		l)read_logs;;
		h)help;;
		v)echo "$version_info"; exit 0;;
		-)
			case "${OPTARG}" in
				continuar)continue_anime;;
				logs)read_logs;;
				help) help;;
				version) echo "$version_info"; exit 0;;
				*) echo -e "${red}--${OPTARG} isn't a valid flag!${def}">&2; exit 1;;
			esac;;
		?) echo -e "${red}-${OPTARG} isn't a valid flag!${def}">&2; exit 1;;
	esac
done

function main(){
	if [ ! -d /tmp/oveja/ ]; then mkdir /tmp/oveja/ &>/dev/null; fi
	if [ ! -d $HOME/.config/oveja/ ]; then mkdir $HOME/.config/oveja/ &>/dev/null; fi
	echo -e "${bold}Mee... 🐑${def}"
	echo -ne "${bold}Buscar anime: ${def}"; read raw_text
	text_query=$(echo -n "$raw_text" | perl -pe 's/([^a-zA-Z0-9\Q.-_\E])/sprintf("%%%02X", ord($1))/ge')
	search_anime "$text_query"
	exit 0
}

main

# Adapted from github.com/pystardust/ani-cli
# oveja.sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Project repository: https://github.com/jirentorres/oveja
